### ISSUE TITLE
[TODO] improve IDE

### ISSUE THREAD

**Issue by jLn0n** [jLn0n/executor-gui#1]
- [ ]  infinite text limit(idk how to do this but it might be possible)
- [ ]  optimize syntax highlight(lags when more lines are in)
- [ ]  customisable highlight colors :D
